name: CI2

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Trass3r/setup-cpp@master
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: hendrikmuhs/ccache-action@main
      with:
        max-size: 1G
        verbose: 1
    - name: build
      run: |
        mkdir build && cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX=$PWD\..\install -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DHLSLCC_LIBRARY_SHARED=OFF ..
        ninja install
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          install/*
